version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - "${NGINX_PORT}:80"
    volumes_from:
      - app
    volumes:
      - ./nginx/log:/var/log/nginx
    networks:
      - rails-network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./app/rails-app:/app/rails-app
    environment:
      - TZ=${TZ}
      - POSTGRES_DEV_USER=${POSTGRES_DEV_USER}
      - POSTGRES_DEV_PASS=${POSTGRES_DEV_PASS}
      - RUBY_DEBUG_OPEN=true rails server
    tty: true
    networks:
      - rails-network

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "${POSTGRES_DEV_PORT}:5432"
    volumes:
      - db-store-dev:/var/lib/postgresql/data
      - ./db/log:/var/log
    environment:
      - TZ=${TZ}
      - POSTGRES_USER=${POSTGRES_DEV_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DEV_PASS}
    networks:
      - rails-network

volumes:
  db-store-dev:

networks:
  rails-network:
